### ISSUE TITLE
“更新公式的合理性可以在数学上证明”--是哪方面的合理性？

### ISSUE THREAD

**Issue by A-Pai** [PiperLiu/Reinforcement-Learning-practice-zh#1]
您的整理和解释工作很好，受益匪浅！十分感谢，继续请教：
“梯度赌博机算法中，偏好函数更新：梯度上升公式是精确梯度上升的随机近似的证明.md”中讲到“更新公式的合理性可以在数学上证明”--是哪方面的合理性？是收敛性吗？
老外写的书，前沿、有深度，但是阐述得似乎不系统

**Comment by PiperLiu** [comment]
老师您好，据我的理解应该是包括收敛性的，就是如此更新，是符合该变量本身的定义的，会让该变量收敛到其真实值
